services:
  app:
    build: .
    container_name: smb-chatbot-app
    ports:
      - "${PORT:-8080}:8080"
    environment:
      PORT: ${PORT:-8080}
      DATABASE_URL: "postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-postgres}?sslmode=disable"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    command: |
      sh -c '
        echo "Waiting for DB..."
        sleep 5

        echo "Running migrations..."
        # Loop until migrate command succeeds
        until migrate -database "$$DATABASE_URL" -path /migrations up; do
          echo "Migration failed, retrying in 5s..."
          sleep 5
        done

        echo "Migrations complete, starting app..."
        # Execute the main application binary
        exec /smb-chatbot
      '

  db:
    image: postgres:15-alpine 
    container_name: smb-chatbot-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres} 
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: {}